[build]
builder = "dockerfile"
dockerfilePath = "./gemini_fastapi/Dockerfile.railway"



[services.web]
tcpProxyApplicationPort = 8000

[services.redis]
image = "redis:7-alpine"
command = "redis-server --appendonly yes"
